-- ============================================================
-- SEIMEI HUB — Tables pour les 8 modules (sutures existe déjà)
-- ============================================================

-- ── BRÛLURES ─────────────────────────────────────────────
create table if not exists brulures_scores (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  name text not null, correct int, total int, score int, grade text
);
alter table brulures_scores enable row level security;
create policy "ins_brul" on brulures_scores for insert to anon with check (true);
create policy "sel_brul" on brulures_scores for select to anon using (true);

-- ── FRACTURES ────────────────────────────────────────────
create table if not exists fractures_scores (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  name text not null, correct int, total int, score int, grade text
);
alter table fractures_scores enable row level security;
create policy "ins_frac" on fractures_scores for insert to anon with check (true);
create policy "sel_frac" on fractures_scores for select to anon using (true);

-- ── ATTELLES ─────────────────────────────────────────────
create table if not exists attelle_scores (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  name text not null, correct int, total int, score int, grade text
);
alter table attelle_scores enable row level security;
create policy "ins_att" on attelle_scores for insert to anon with check (true);
create policy "sel_att" on attelle_scores for select to anon using (true);

-- ── RCR ──────────────────────────────────────────────────
create table if not exists rcr_scores (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  name text not null, correct int, total int, score int, grade text
);
alter table rcr_scores enable row level security;
create policy "ins_rcr" on rcr_scores for insert to anon with check (true);
create policy "sel_rcr" on rcr_scores for select to anon using (true);

-- ── PRÉLÈVEMENT SANGUIN ──────────────────────────────────
create table if not exists prelevement_scores (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  name text not null, correct int, total int, score int, grade text
);
alter table prelevement_scores enable row level security;
create policy "ins_prel" on prelevement_scores for insert to anon with check (true);
create policy "sel_prel" on prelevement_scores for select to anon using (true);

-- ── BANDAGE COMPRESSIF ───────────────────────────────────
create table if not exists bandage_scores (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  name text not null, correct int, total int, score int, grade text
);
alter table bandage_scores enable row level security;
create policy "ins_band" on bandage_scores for insert to anon with check (true);
create policy "sel_band" on bandage_scores for select to anon using (true);

-- ── POSE DE GARROT ───────────────────────────────────────
create table if not exists garrot_scores (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  name text not null, correct int, total int, score int, grade text
);
alter table garrot_scores enable row level security;
create policy "ins_gar" on garrot_scores for insert to anon with check (true);
create policy "sel_gar" on garrot_scores for select to anon using (true);

-- ── RÉDUCTION D'ÉPAULE ───────────────────────────────────
create table if not exists epaule_scores (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  name text not null, correct int, total int, score int, grade text
);
alter table epaule_scores enable row level security;
create policy "ins_ep" on epaule_scores for insert to anon with check (true);
create policy "sel_ep" on epaule_scores for select to anon using (true);

-- ── QUIZ PHARMACOLOGIE ──────────────────────────────────
create table if not exists pharma_scores (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  name text not null, correct int, total int, score int, grade text
);
alter table pharma_scores enable row level security;
create policy "ins_pharma" on pharma_scores for insert to anon with check (true);
create policy "sel_pharma" on pharma_scores for select to anon using (true);

-- ── CONSTANTES VITALES ───────────────────────────────────
create table if not exists constantes_scores (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  name text not null, correct int, total int, score int, grade text
);
alter table constantes_scores enable row level security;
create policy "ins_const" on constantes_scores for insert to anon with check (true);
create policy "sel_const" on constantes_scores for select to anon using (true);

-- ── QUIZ NINJUTSU MÉDICAL ────────────────────────────────
create table if not exists ninjutsu_scores (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  name text not null, correct int, total int, score int, grade text
);
alter table ninjutsu_scores enable row level security;
create policy "ins_ninj" on ninjutsu_scores for insert to anon with check (true);
create policy "sel_ninj" on ninjutsu_scores for select to anon using (true);

-- ── QUIZ PAR COURS (Anatomie, Fondamentaux, Protocoles, Articulations,
--    Chirurgie, Psychologie, Botanique, Poisons, Recensement) ────────
create table if not exists course_quiz_scores (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  name text not null, course text not null,
  correct int, total int, score int, grade text
);
alter table course_quiz_scores enable row level security;
create policy "ins_cq" on course_quiz_scores for insert to anon with check (true);
create policy "sel_cq" on course_quiz_scores for select to anon using (true);

-- ── ÉVALUATION SECOURISTE DE TERRAIN ─────────────────────
create table if not exists eval_secouriste_scores (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  name text not null, correct int, total int, score int, grade text,
  terrain_reussi boolean, apte boolean
);
alter table eval_secouriste_scores enable row level security;
create policy "ins_eval" on eval_secouriste_scores for insert to anon with check (true);
create policy "sel_eval" on eval_secouriste_scores for select to anon using (true);

-- ── ATELIER FONDAMENTAUX ─────────────────────────────────
create table if not exists fondamentaux_scores (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  name text not null, correct int, total int, score int, grade text
);
alter table fondamentaux_scores enable row level security;
create policy "ins_fond" on fondamentaux_scores for insert to anon with check (true);
create policy "sel_fond" on fondamentaux_scores for select to anon using (true);

-- ── ATELIER PROTOCOLES D'URGENCE ─────────────────────────
create table if not exists protocoles_scores (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  name text not null, correct int, total int, score int, grade text
);
alter table protocoles_scores enable row level security;
create policy "ins_proto" on protocoles_scores for insert to anon with check (true);
create policy "sel_proto" on protocoles_scores for select to anon using (true);

-- ── ATELIER REGISTRE DES POISONS ─────────────────────────
create table if not exists poisons_scores (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  name text not null, correct int, total int, score int, grade text
);
alter table poisons_scores enable row level security;
create policy "ins_pois" on poisons_scores for insert to anon with check (true);
create policy "sel_pois" on poisons_scores for select to anon using (true);

-- ── ATELIER ARTICULATIONS ────────────────────────────────
create table if not exists articulations_scores (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  name text not null, correct int, total int, score int, grade text
);
alter table articulations_scores enable row level security;
create policy "ins_artic" on articulations_scores for insert to anon with check (true);
create policy "sel_artic" on articulations_scores for select to anon using (true);

-- ── ATELIER CHIRURGIE ────────────────────────────────────
create table if not exists chirurgie_scores (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  name text not null, correct int, total int, score int, grade text
);
alter table chirurgie_scores enable row level security;
create policy "ins_chir" on chirurgie_scores for insert to anon with check (true);
create policy "sel_chir" on chirurgie_scores for select to anon using (true);

-- ── HIÉRARCHIE SEIMEI ───────────────────────────────────
create table if not exists seimei_hierarchie (
  id bigint generated by default as identity primary key,
  rang text not null,
  membre text not null default '',
  ordre int not null default 0,
  created_at timestamptz default now()
);
alter table seimei_hierarchie enable row level security;
create policy "ins_hier" on seimei_hierarchie for insert to anon with check (true);
create policy "sel_hier" on seimei_hierarchie for select to anon using (true);
create policy "upd_hier" on seimei_hierarchie for update to anon using (true) with check (true);
create policy "del_hier" on seimei_hierarchie for delete to anon using (true);
